# Numpy Functions:

In [1]:
import numpy as np

# arange()

In [2]:
arr_1d=np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
even_arr=np.arange(1,13,2)
print(even_arr)

[ 1  3  5  7  9 11]


# linspace()


In [4]:
np.linspace(1,5,4)


array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()


In [16]:
ar_2d=arr_1d.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
ar_3d=arr_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
ar_2d=np.arange(1,13).reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()


In [8]:
ar_2d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [24]:
ar_2d.flatten('F')

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

# transpose()

In [10]:
ar_2d.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])