In [1]:
import numpy as np

In [2]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])

In [3]:
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
mx_1s=np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [7]:
mx_1s.dtype

dtype('float64')

In [9]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
mx_1s=np.ones((3,4),dtype=str)
print(mx_1s)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [11]:
mx_0s=np.zeros((4,4))
print(mx_0s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
mx_0s=np.zeros((4,4),dtype=str)
print(mx_0s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [17]:
em_mx=np.empty((3,3))
print(em_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.15407055e-321]
 [1.69121367e-306 2.56761491e-312 2.56761491e-312]]
